package service

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Service represents an onion service
type Service struct {
	Path string
}

// New creates a new Service instance
func New(path string) (*Service, error) {
	absPath, err := filepath.Abs(path)
	if err != nil {
		return nil, fmt.Errorf("failed to resolve path: %w", err)
	}

	return &Service{Path: absPath}, nil
}

// GenerateTorrc creates a torrc file by combining paths with manager.conf
func (s *Service) GenerateTorrc() error {
	torrcPath := filepath.Join(s.Path, "torrc")
	managerConfPath := filepath.Join(s.Path, "manager.conf")
	hiddenServiceDir := filepath.Join(s.Path, "data", "hidden_service")
	torDataDir := filepath.Join(s.Path, "data", "tor_data")

	// Read user's manager.conf
	userConfig, err := os.ReadFile(managerConfPath)
	if err != nil {
		return fmt.Errorf("failed to read manager.conf: %w", err)
	}

	// Remove the header comment line if it exists
	userConfigStr := string(userConfig)
	headerComment := "# Edit torrc options except HiddenServiceDir and DataDirectory here\n"
	if strings.HasPrefix(userConfigStr, headerComment) {
		userConfigStr = strings.TrimPrefix(userConfigStr, headerComment)
		// Also trim any extra newlines after the header
		userConfigStr = strings.TrimLeft(userConfigStr, "\n")
	}

	// Build torrc with dynamic paths + user config
	var builder strings.Builder
	builder.WriteString("# This file is generated by onionmanager. Edit manager.conf instead\n")
	builder.WriteString(fmt.Sprintf("HiddenServiceDir %s\n", hiddenServiceDir))
	builder.WriteString(fmt.Sprintf("DataDirectory %s\n", torDataDir))
	builder.WriteString("\n# User configuration from manager.conf\n")
	builder.WriteString(userConfigStr)

	return os.WriteFile(torrcPath, []byte(builder.String()), 0644)
}

// ReadOnionAddress reads the .onion address from the hostname file
func (s *Service) ReadOnionAddress() (string, error) {
	hostnamePath := filepath.Join(s.Path, "data", "hidden_service", "hostname")
	data, err := os.ReadFile(hostnamePath)
	if err != nil {
		return "", fmt.Errorf("failed to read hostname: %w", err)
	}

	return strings.TrimSpace(string(data)), nil
}

// ManagerConfPath returns the path to manager.conf
func (s *Service) ManagerConfPath() string {
	return filepath.Join(s.Path, "manager.conf")
}

// TorrcPath returns the path to torrc
func (s *Service) TorrcPath() string {
	return filepath.Join(s.Path, "torrc")
}

// DataDir returns the path to the data directory
func (s *Service) DataDir() string {
	return filepath.Join(s.Path, "data")
}
